# Generated by Django 4.2.7 on 2025-11-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='server_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
